(:name dockerfile-mode
       :description "An emacs mode for handling Dockerfiles."
       :type github
       :pkgname "spotify/dockerfile-mode"
       :prepare (progn
                  (add-to-list 'auto-mode-alist
                               '("Dockerfile\\'" . dockerfile-mode))))
